services:
  - type: web
    name: Bousoufi_Note
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./run.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 8000